remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-remote-theme
title: "Geometric Fitting Problems"
description: Documentation for the Geometric Fitting Problems package.
color_scheme: dark
markdown: kramdown
url: "https://marcelo-raf.github.io"
baseurl: "/GeometricFittingProblems"
