theme: minima
title: Geometric Fitting Problems
description: Documentation for the Geometric Fitting Problems package.
markdown: kramdown

minima:
  custom_css:
    - assets/css/custom.css

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: "highlight"

nav:
  - title: Home
    url: /
  - title: Installation
    url: /installation/
  - title: Examples
    url: /examples/
  - title: How to Use
    url: /how_to_use/
