theme: just-the-docs
title: Geometric Fitting Problems
description: Documentation for the Geometric Fitting Problems package.
color_scheme: dark
url: "https://marcelo-raf.github.io"
baseurl: "/GeometricFittingProblems"
