name: Build and Deploy Jekyll

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
          bundler-cache: true

      - name: Install dependencies
        working-directory: ./docs
        run: |
          gem install bundler
          bundle install
          gem install jekyll

      - name: Build site
        working-directory: ./docs
        run: bundle exec jekyll build --trace --destination ./docs/_site
