name: Build and Deploy Jekyll

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        run: gem install bundler:2.6.2

      - name: Install dependencies
        working-directory: ./docs
        run: |
          bundle config set path 'vendor/bundle'
          bundle install

      - name: Build site
        working-directory: ./docs
        run: bundle exec jekyll build --source . --destination ../_site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
