name: Build and Deploy Jekyll

on:
  push:
    branches:
      - main # Altere para sua branch principal, se necessário

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build site
        run: bundle exec jekyll build --source ./docs --destination ./docs/_site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_site
