name: Build and Deploy Jekyll

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        - name: Install dependencies
          run: |
                gem install bundler:2.3.27
                bundle install --path vendor/bundle


      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --path vendor/bundle

      - name: Build site
        run: bundle exec jekyll build --source ./docs --destination ./_site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
